// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjFC7ysT_Z72gsX9kExHY1PhhF8JRY9qA',
    appId: '1:886837966090:web:c34cb6f779e0a095f436f3',
    messagingSenderId: '886837966090',
    projectId: 'pronouncekiswahili',
    authDomain: 'pronouncekiswahili.firebaseapp.com',
    storageBucket: 'pronouncekiswahili.appspot.com',
    measurementId: 'G-J6PTN6WDEV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATqt5vGt1i1NQDKKnBqYYGq3VlJxiiS3s',
    appId: '1:886837966090:android:ddff009f4e44c969f436f3',
    messagingSenderId: '886837966090',
    projectId: 'pronouncekiswahili',
    storageBucket: 'pronouncekiswahili.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr0caIqbyOQ__0uUBZ9F7KeZ-FeoLQpv4',
    appId: '1:886837966090:ios:eadd27917c96abedf436f3',
    messagingSenderId: '886837966090',
    projectId: 'pronouncekiswahili',
    storageBucket: 'pronouncekiswahili.appspot.com',
    iosClientId: '886837966090-di4td4o603l8kbtee6vv59k9p3avri0f.apps.googleusercontent.com',
    iosBundleId: 'com.example.pronounceKiswahili',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr0caIqbyOQ__0uUBZ9F7KeZ-FeoLQpv4',
    appId: '1:886837966090:ios:eadd27917c96abedf436f3',
    messagingSenderId: '886837966090',
    projectId: 'pronouncekiswahili',
    storageBucket: 'pronouncekiswahili.appspot.com',
    iosClientId: '886837966090-di4td4o603l8kbtee6vv59k9p3avri0f.apps.googleusercontent.com',
    iosBundleId: 'com.example.pronounceKiswahili',
  );
}
